// flow-typed signature: 9e56e6cbfda5e854111690e3fd2185ca
// flow-typed version: <<STUB>>/babel-plugin-__coverage___v11.0.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-__coverage__'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-__coverage__' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-__coverage__/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-__coverage__/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-__coverage__/lib/index'>;
}
