// flow-typed signature: de8c0123a285b725a18e6144466ed32d
// flow-typed version: <<STUB>>/eslint-config-babel_v^7.0.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-babel/index' {
  declare module.exports: $Exports<'eslint-config-babel'>;
}
declare module 'eslint-config-babel/index.js' {
  declare module.exports: $Exports<'eslint-config-babel'>;
}
