// flow-typed signature: 796e2c8eddd7de0e5201746d774affdc
// flow-typed version: <<STUB>>/babel-preset-survivejs-kanban_v^0.3.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-survivejs-kanban'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-survivejs-kanban' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-survivejs-kanban/index' {
  declare module.exports: $Exports<'babel-preset-survivejs-kanban'>;
}
declare module 'babel-preset-survivejs-kanban/index.js' {
  declare module.exports: $Exports<'babel-preset-survivejs-kanban'>;
}
